services:
  api:
    container_name: agents-api
    image: agents-framework:latest
    command: bash -c "alembic upgrade head && uvicorn app.main:socket_app --host 0.0.0.0 --port 8080"
    env_file:
      - .env
    environment:
      - POSTGRES_SERVER=database
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy
  ui:
    container_name: agents-ui
    image: agents-framework-ui:latest
    ports:
      - "8501:8501"
    environment:
        - API_HOST=api
    depends_on:
      - api
  database:
    container_name: agents-db
    image: postgres:latest
    env_file:
      - .env
    environment:
        - POSTGRES_USER=${POSTGRES_USER:-postgres}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
        - POSTGRES_DB=${POSTGRES_DB:-app}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-app}
      interval: 3s
      retries: 10
      start_period: 30s
      timeout: 10s
volumes:
  postgres_data: