services:
  backend:
    image: agents-framework:latest
    env_file:
      - .env
    environment:
      - POSTGRES_SERVER=database
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy
  database:
    image: postgres:latest
    env_file:
      - .env
    environment:
        - POSTGRES_USER=${POSTGRES_USER:-postgres}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
        - POSTGRES_DB=${POSTGRES_DB:-app}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-app}
      interval: 5s
      retries: 10
      start_period: 30s
      timeout: 10s
volumes:
  postgres_data: