"""missing fkeys

Revision ID: 149cab87ab4a
Revises: ca81f9c68596
Create Date: 2024-12-29 18:26:47.604130

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "149cab87ab4a"
down_revision: str | None = "ca81f9c68596"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "actionconditionoperator",
        "root_id",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    op.create_foreign_key(
        "fk_parent_id",
        "actionconditionoperator",
        "actionconditionoperator",
        ["parent_id"],
        ["id"],
    )
    op.create_foreign_key(
        "fk_root_id",
        "actionconditionoperator",
        "actionconditionoperator",
        ["root_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_parent_id", "actionconditionoperator", type_="foreignkey")
    op.drop_constraint("fk_root_id", "actionconditionoperator", type_="foreignkey")
    op.alter_column(
        "actionconditionoperator",
        "root_id",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    # ### end Alembic commands ###
