"""Action conditions

Revision ID: 7cc45942f105
Revises: 6b8ca1e5a098
Create Date: 2024-12-01 12:44:39.101546

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7cc45942f105"
down_revision: str | None = "87f37185bb0c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "actionconditionoperator",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("root_id", sa.Integer(), nullable=False),
        sa.Column(
            "logical_operator",
            sa.Enum("AND", "OR", name="logicaloperator", native_enum=False),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "actioncondition", sa.Column("parent_id", sa.Integer(), nullable=False)
    )
    op.add_column("actioncondition", sa.Column("root_id", sa.Integer(), nullable=False))
    op.add_column(
        "actioncondition",
        sa.Column(
            "state_variable_name",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
        ),
    )
    op.add_column(
        "actioncondition",
        sa.Column(
            "comparison",
            sa.Enum(
                "EQUAL",
                "NOT_EQUAL",
                "GREATER",
                "LESS",
                "AT_LEAST",
                "AT_MOST",
                name="comparisonmethod",
                native_enum=False,
            ),
            nullable=False,
        ),
    )
    op.add_column(
        "actioncondition",
        sa.Column(
            "expected_value",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
        ),
    )
    op.create_foreign_key(
        None, "actioncondition", "actionconditionoperator", ["root_id"], ["id"]
    )
    op.create_foreign_key(
        None,
        "actioncondition",
        "actionconditionoperator",
        ["parent_id"],
        ["id"],
    )
    op.drop_column("actioncondition", "description")
    op.drop_column("actioncondition", "is_active")
    op.drop_column("actioncondition", "name")
    op.drop_column("actioncondition", "value")
    op.drop_constraint(
        "actionconditionmatch_condition_id_fkey",
        "actionconditionmatch",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "actionconditionmatch",
        "actionconditionoperator",
        ["condition_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "actionconditionmatch", type_="foreignkey")
    op.create_foreign_key(
        "actionconditionmatch_condition_id_fkey",
        "actionconditionmatch",
        "actioncondition",
        ["condition_id"],
        ["id"],
    )
    op.add_column(
        "actioncondition",
        sa.Column("value", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "actioncondition",
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "actioncondition",
        sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "actioncondition",
        sa.Column("description", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "actioncondition", type_="foreignkey")
    op.drop_constraint(None, "actioncondition", type_="foreignkey")
    op.drop_column("actioncondition", "expected_value")
    op.drop_column("actioncondition", "comparison")
    op.drop_column("actioncondition", "state_variable_name")
    op.drop_column("actioncondition", "root_id")
    op.drop_column("actioncondition", "parent_id")
    op.drop_table("actionconditionoperator")
    # ### end Alembic commands ###
