"""upgrade_conditions

Revision ID: ca81f9c68596
Revises: 7cc45942f105
Create Date: 2024-12-07 19:48:27.412949

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ca81f9c68596"
down_revision: str | None = "7cc45942f105"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("actionconditionmatch")
    op.add_column(
        "actionconditionoperator",
        sa.Column("action_id", sa.Integer(), nullable=True),
    )
    op.create_foreign_key(
        None, "actionconditionoperator", "action", ["action_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "actionconditionoperator", type_="foreignkey")
    op.drop_column("actionconditionoperator", "action_id")
    op.create_table(
        "actionconditionmatch",
        sa.Column("action_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("condition_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["action_id"],
            ["action.id"],
            name="actionconditionmatch_action_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["condition_id"],
            ["actionconditionoperator.id"],
            name="actionconditionmatch_condition_id_fkey",
        ),
        sa.PrimaryKeyConstraint(
            "action_id", "condition_id", name="actionconditionmatch_pkey"
        ),
    )
    # ### end Alembic commands ###
